name: ulysse_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_facebook_auth: ^6.0.3
  get: ^4.6.6
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  http: ^1.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  test: ^1.24.9

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "asset/images/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/images/logo.jpg"

flutter:
  uses-material-design: true
  # To add asset to your application, add an asset section, like this:
  assets:
    - asset/images/
    - asset/icons/
  fonts:
    - family: Italianno
      fonts:
        - asset: fonts/Italianno-Regular.ttf

    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.ttf
  # see https://flutter.dev/custom-fonts/#from-packages
